# Generated by Django 4.0 on 2021-12-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeesDevicesApi', '0003_upload_alter_device_description_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
